# API Contract: Type Validation Functions
# Internal utility functions - not exposed in public API

openapi: 3.0.0
info:
  title: Type Validators Internal API
  version: 1.0.0
  description: Internal validation utilities for the chronia library

components:
  schemas:
    ValidationResult:
      type: boolean
      description: Result of validation check

    UnknownValue:
      description: Any JavaScript value type
      oneOf:
        - type: string
        - type: number
        - type: boolean
        - type: object
        - type: array
        - type: "null"

paths:
  # Note: These are function contracts, not HTTP endpoints
  /isValidDate:
    post:
      summary: Validate if value is a valid Date instance
      operationId: isValidDate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  $ref: '#/components/schemas/UnknownValue'
              required:
                - value
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
              examples:
                validDate:
                  value: true
                  summary: Valid Date instance
                invalidDate:
                  value: false
                  summary: Invalid Date or non-Date value

  /isValidNumber:
    post:
      summary: Validate if value is a finite number
      operationId: isValidNumber
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  $ref: '#/components/schemas/UnknownValue'
              required:
                - value
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
              examples:
                finiteNumber:
                  value: true
                  summary: Finite number
                nonFiniteNumber:
                  value: false
                  summary: NaN, Infinity, or non-number

  /isValidDateOrNumber:
    post:
      summary: Validate if value is either a valid Date or finite number
      operationId: isValidDateOrNumber
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  $ref: '#/components/schemas/UnknownValue'
              required:
                - value
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
              examples:
                validDate:
                  value: true
                  summary: Valid Date instance
                validNumber:
                  value: true
                  summary: Finite number
                invalid:
                  value: false
                  summary: Neither valid Date nor finite number